<#
.SYNOPSIS
    Starts the ngrok tunnel in front of the local trigger API, verifying the
    whole chain before and after.

.DESCRIPTION
    Order matters. The tunnel is useless if the API behind it is down, and an
    ngrok tunnel pointed at a dead port returns 502 to your web app without any
    obvious cause. So this checks the API FIRST and refuses to start otherwise.

    After the tunnel is up it reads the public URL from ngrok's local admin API
    (127.0.0.1:4040) and runs a real authenticated request end-to-end, so a
    green message means traffic actually flowed - not merely that a process
    started.

.EXAMPLE
    .\ngrok\start_tunnel.ps1
.EXAMPLE
    .\ngrok\start_tunnel.ps1 -StartApi     # also launch the API if it is down
#>
[CmdletBinding()]
param(
    [int]    $Port     = 8000,
    [switch] $StartApi,
    [string] $NgrokExe
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot

# --- Locate the agent ------------------------------------------------------
# Checked in preference order: an explicit path, then a current manual install,
# then whatever is on PATH, then the winget package directory (which winget
# aliases but does not always put on PATH until the shell restarts).
if (-not $NgrokExe) {
    # @(...) around the pipeline is load-bearing: with a single surviving
    # candidate the pipeline returns a bare STRING, and [0] on a string yields
    # its first character ("C") rather than the path.
    $candidates = @(
        @(
            'C:\ngrok\ngrok.exe',
            (Get-Command ngrok -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
            "$env:LOCALAPPDATA\Microsoft\WinGet\Packages\Ngrok.Ngrok_Microsoft.Winget.Source_8wekyb3d8bbwe\ngrok.exe"
        ) | Where-Object { $_ -and (Test-Path $_) }
    )
    if ($candidates.Count -eq 0) {
        throw "ngrok not found. Install it (winget install ngrok.ngrok) or pass -NgrokExe."
    }

    # Existing on disk is not the same as runnable: Windows Defender quarantines
    # ngrok.exe as PUA, leaving a full-size file that dies with "contains a
    # virus" the moment it is executed. Pick the first one that actually runs.
    $NgrokExe = $null
    foreach ($c in $candidates) {
        try {
            $null = & $c version 2>&1
            if ($LASTEXITCODE -eq 0) { $NgrokExe = $c; break }
        } catch { }
        Write-Warning "Skipping unrunnable ngrok at $c (quarantined? see ngrok/README.md)"
    }
    if (-not $NgrokExe) {
        throw ("Found ngrok on disk but none of the copies would run. " +
               "Windows Defender flags ngrok.exe as PUA - see the Defender note " +
               "in ngrok/README.md. Candidates: " + ($candidates -join ', '))
    }
}
Write-Host "ngrok: $NgrokExe" -ForegroundColor DarkGray

# --- 1. The API must be up FIRST -------------------------------------------
function Test-Api {
    try {
        $r = Invoke-RestMethod "http://127.0.0.1:$Port/health" -TimeoutSec 3
        return $r.status -eq 'ok'
    } catch { return $false }
}

if (-not (Test-Api)) {
    if (-not $StartApi) {
        throw ("The API is not answering on http://127.0.0.1:$Port/health. " +
               "Start it with 'python -m src.api', or re-run this with -StartApi. " +
               "Publishing a tunnel to a dead port just yields 502s.")
    }
    Write-Host "Starting the API..." -ForegroundColor Yellow
    $py = if (Test-Path "$repo\.venv\Scripts\python.exe") { "$repo\.venv\Scripts\python.exe" }
          else { (Get-Command python).Source }
    Start-Process -FilePath $py -ArgumentList '-m','src.api' -WorkingDirectory $repo `
                  -WindowStyle Hidden
    $deadline = (Get-Date).AddSeconds(30)
    while ((Get-Date) -lt $deadline -and -not (Test-Api)) { Start-Sleep -Milliseconds 500 }
    if (-not (Test-Api)) { throw "The API did not come up within 30s. Run 'python -m src.api' directly to see why." }
}
Write-Host "[ok] API healthy on 127.0.0.1:$Port" -ForegroundColor Green

# --- 2. The authtoken must be registered -----------------------------------
# Without it the agent starts and dies with ERR_NGROK_4018, which is easy to
# miss when it is backgrounded.
$globalCfg = "$env:LOCALAPPDATA\ngrok\ngrok.yml"
if (-not (Test-Path $globalCfg) -or
    -not (Select-String -Path $globalCfg -Pattern 'authtoken' -Quiet -ErrorAction SilentlyContinue)) {
    throw ("No ngrok authtoken registered. Get one from " +
           "https://dashboard.ngrok.com/get-started/your-authtoken then run:`n" +
           "  & '$NgrokExe' config add-authtoken YOUR_TOKEN")
}

# --- 3. Start the tunnel ----------------------------------------------------
Get-Process ngrok -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Milliseconds 500

# The traffic policy is INLINE in ngrok.yml (generated by build_config.py):
# `ngrok start` has no --traffic-policy-file flag, and a file reference under
# `endpoints:` is rejected by the server as ERR_NGROK_9026.
$repoCfg = Join-Path $PSScriptRoot 'ngrok.yml'
Start-Process -FilePath $NgrokExe `
    -ArgumentList @('start','vfs-webhook','--config',"`"$globalCfg`"",'--config',"`"$repoCfg`"") `
    -WindowStyle Hidden

# --- 4. Read the public URL from the local admin API ------------------------
$publicUrl = $null
$deadline  = (Get-Date).AddSeconds(20)
while ((Get-Date) -lt $deadline -and -not $publicUrl) {
    Start-Sleep -Milliseconds 500
    try {
        $t = (Invoke-RestMethod 'http://127.0.0.1:4040/api/tunnels' -TimeoutSec 2).tunnels
        $publicUrl = ($t | Where-Object { $_.proto -eq 'https' } | Select-Object -First 1).public_url
    } catch { }
}
if (-not $publicUrl) {
    throw ("The tunnel did not report a public URL. Run it in the foreground to see the error:`n" +
           "  & '$NgrokExe' start vfs-webhook --config '$globalCfg' --config '$repoCfg'")
}
Write-Host "[ok] Tunnel up: $publicUrl" -ForegroundColor Green

# --- 5. Prove it end to end -------------------------------------------------
# A started process is not a working tunnel. This is the check that matters.
$token = $env:VFSAPI_SECRET_TOKEN
if (-not $token -and (Test-Path "$repo\.env.api")) {
    $line = Select-String -Path "$repo\.env.api" -Pattern '^VFSAPI_SECRET_TOKEN=(.+)$'
    if ($line) { $token = $line.Matches[0].Groups[1].Value.Trim() }
}

try {
    $h = Invoke-RestMethod "$publicUrl/health" -TimeoutSec 10 `
            -Headers @{ 'ngrok-skip-browser-warning' = 'true' }
    Write-Host "[ok] /health through the tunnel: $($h.status)" -ForegroundColor Green
} catch {
    Write-Warning "Tunnel is up but /health failed through it: $_"
}

if ($token) {
    try {
        $null = Invoke-RestMethod "$publicUrl/clients" -TimeoutSec 10 -Headers @{
            'X-Webhook-Secret-Token'    = $token
            'ngrok-skip-browser-warning'= 'true'
        }
        Write-Host "[ok] Authenticated request through the tunnel succeeded" -ForegroundColor Green
    } catch {
        Write-Warning "Authenticated request failed: $_"
    }
    # An unauthenticated call MUST be refused. If this ever returns 200 the
    # tunnel is exposing the API without auth, which is the one unacceptable
    # outcome - so it is checked explicitly rather than assumed.
    try {
        $null = Invoke-RestMethod "$publicUrl/clients" -TimeoutSec 10 `
                    -Headers @{ 'ngrok-skip-browser-warning' = 'true' }
        Write-Host "[FAIL] /clients answered WITHOUT a token. Do not use this tunnel." -ForegroundColor Red
    } catch {
        Write-Host "[ok] Unauthenticated request correctly refused" -ForegroundColor Green
    }
} else {
    Write-Warning "No VFSAPI_SECRET_TOKEN found; skipped the authenticated checks."
}

Write-Host ""
Write-Host "Public base URL for your web app:" -ForegroundColor Cyan
Write-Host "  $publicUrl" -ForegroundColor White
Write-Host "Inspect live traffic at http://127.0.0.1:4040" -ForegroundColor DarkGray
Write-Host "Stop with: Get-Process ngrok | Stop-Process" -ForegroundColor DarkGray
