[vfs-url]
;AE-CZE = https://visa.vfsglobal.com/are/en/cze/login
;AE-CHE = https://visa.vfsglobal.com/are/en/che/login
;AE-FRA = https://visa.vfsglobal.com/are/en/fra/login
;AE-HUN = https://visa.vfsglobal.com/are/en/hun/login
AE-ITA = https://visa.vfsglobal.com/are/en/ita/login
;AE-LUX = https://visa.vfsglobal.com/are/en/lux/login
;AE-MT = https://visa.vfsglobal.com/are/en/mlt/login